DECLARE @json NVARCHAR(MAX);
SET @json = N'{"kaka"[{ "Timestamp": "9/11/2019 0:47:40", "Employment Type": "Full-time", "Company Name": "Citi", "Company Size - # Employees": "10,000-100,000", "Primary Location (Country)": "United States (US)", "Primary Location (City)": "Manhattan", "Industry in Company": "Finance", "Public or Private Company": "Public", "Years Experience in Industry": "10-20", "Years of Experience in Current Company": "2-5", "Job Title In Company": "Senior Vice President", "Job Ladder": "Management", "Job Level": "1 (I)", "Required Hours Per Week": "40+", "Actual Hours Per Week": "50-70", "Highest Level of Formal Education Completed": "Graduate Degree", "Total Base Salary in 2018 (in USD)": "180000", "Total Bonus in 2018 (cumulative annual value in USD)": "40000", "Total Stock Options/Equity in 2018 (cumulative annual value in USD)": "0", "Health Insurance Offered": "Yes", "Annual Vacation (in Weeks)": "4", "Are you happy at your current position?": "It s Complicated", "Do you plan to resign in the next 12 months?": "Yes", "What are your thoughts about the direction of your industry?": "", "Gender": "Male", "Final Question: What are the top skills (you define what that means) that you believe will be necessary for job growth in your industry over the next 10 years?": "", "Have you ever done a bootcamp? If so was it worth it?": "" },
    { "Timestamp": "9/11/2019 0:51:26", "Employment Type": "Full-time", "Company Name": "Ibm", "Company Size - # Employees": "10,000-100,000", "Primary Location (Country)": "United States (US)", "Primary Location (City)": "", "Industry in Company": "Software", "Public or Private Company": "Public", "Years Experience in Industry": "10-20", "Years of Experience in Current Company": "10-20", "Job Title In Company": "Senior data engineer", "Job Ladder": "Dev-Ops", "Job Level": "None", "Required Hours Per Week": "40+", "Actual Hours Per Week": "40-50", "Highest Level of Formal Education Completed": "Undergraduate Degree", "Total Base Salary in 2018 (in USD)": "151000", "Total Bonus in 2018 (cumulative annual value in USD)": "22000", "Total Stock Options/Equity in 2018 (cumulative annual value in USD)": "0", "Health Insurance Offered": "Yes", "Annual Vacation (in Weeks)": "5", "Are you happy at your current position?": "No", "Do you plan to resign in the next 12 months?": "No", "What are your thoughts about the direction of your industry?": "", "Gender": "Male", "Final Question: What are the top skills (you define what that means) that you believe will be necessary for job growth in your industry over the next 10 years?": "", "Have you ever done a bootcamp? If so was it worth it?": "" },}]';


SELECT *
from OPENJSON(@json, '$.kaka')
with(
    id int '$.kaka.Timestamp'
);